### ISSUE TITLE
UNet Error :)

### ISSUE THREAD

**Issue by shuklaji28** [dtransposed/code_videos#1]
Forward Diffusion worked well. But right after that, I installed unet using - 
`pip install unet`

And while predicting noise, i'am getting this error : UNet.forward() takes 2 positional arguments but 3 were given.

I'm only passing two arguments but still getting this error. Any help guys? Why is this happening?

**Comment by dtransposed** [comment]
Why would you `pip install unet`? `unet` is not a dependency for this Jupyter notebook.

**Comment by shuklaji28** [comment]
> Why would you `pip install unet`? `unet` is not a dependency for this Jupyter notebook.

Damn GODDDDD, my bad :) Just saw------scrolled DOWNNNNNNNNNN:) 

 I was following your video and after implementing forward diffusion, you wrote that code importing unet. I thought i need to install that before using :( damn,silly :( I spent a day solving this error which never occured :) I should have just watched the video for next 10 minutes maybe :) I'm crying and laughing at the same time :)  Thanks :) Do you know i just messaged that person who made that library asking him to resolve this error in my code. I sent him my whole code :) He'll report me ig :) Not bad :) New lesson learnt :)
